# Generated by Django 5.2.14 on 2026-05-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_order_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='rider_latitude',
            field=models.DecimalField(decimal_places=6, default=14.599512, max_digits=9),
        ),
        migrations.AlterField(
            model_name='order',
            name='rider_longitude',
            field=models.DecimalField(decimal_places=6, default=120.984222, max_digits=9),
        ),
    ]
