# Generated by Django 5.2.14 on 2026-05-16 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_order_rider_latitude_and_more'),
        ('menu', '0008_food_order_payments_review'),
    ]

    operations = [
    ]
