# Generated by GitHub Copilot

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_merge_20260516_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_type',
            field=models.CharField(choices=[('Dine In', 'Dine In'), ('Pickup', 'Pickup'), ('Delivery', 'Delivery')], default='Delivery', max_length=20),
        ),
    ]
