# Generated by Django 5.2.14 on 2026-05-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_order_delivery_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='flavor_choice',
            field=models.CharField(blank=True, choices=[('Cheese', 'Cheese'), ('Sour Cream', 'Sour Cream'), ('Salt', 'Salt'), ('BBQ', 'BBQ')], max_length=30),
        ),
    ]
