# Generated by Django 5.2.17 on 2026-08-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_promo_code_and_order_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='rider_latitude',
            field=models.DecimalField(decimal_places=6, default=9.539611, max_digits=9),
        ),
        migrations.AlterField(
            model_name='order',
            name='rider_longitude',
            field=models.DecimalField(decimal_places=6, default=125.838139, max_digits=9),
        ),
    ]
